name: StartServer

on:
  repository_dispatch:
  workflow_dispatch:

concurrency: 
  group: server
  cancel-in-progress: true

jobs:
  StartServer:
    runs-on: ubuntu-latest
    name: Server
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - name: Server Install
        run: |
          mkdir downloads
          cd downloads
          #install sonarr
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 2009837CBFFD68F45BC180471F4F90DE2A9B4BF8
          echo "deb https://apt.sonarr.tv/ubuntu focal main" | sudo tee /etc/apt/sources.list.d/sonarr.list
          sudo apt update
          sudo apt install sonarr
          #install radarr
          sudo useradd radarr
          wget --content-disposition 'http://radarr.servarr.com/v1/update/master/updatefile?os=linux&runtime=netcore&arch=x64'
          tar -xvzf Radarr*.linux*.tar.gz
          sudo mv Radarr/ /opt
          sudo chown radarr:radarr /opt/Radarr 
          sudo /opt/Radarr/Radarr -nobrowser & sudo npx localtunnel --port 7878 --subdomain radarr1
          #install qbittorrent
          
