name: StartServer

on:
  repository_dispatch:
  workflow_dispatch:
  
concurrency: 
  group: server
  cancel-in-progress: true
    
jobs:
  StartServer:
    runs-on: ubuntu-latest
    name: Server
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - name: Server Install
        run: |
          sudo docker --help
          
          
