name: StartServer

on:
  repository_dispatch:
  workflow_dispatch:

concurrency: 
  group: server
  cancel-in-progress: true

jobs:
  StartServer:
    runs-on: ubuntu-latest
    name: Server
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - name: Server Install
        run: |
          mkdir downloads
          cd downloads
          #install sonarr
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 2009837CBFFD68F45BC180471F4F90DE2A9B4BF8
          echo "deb https://apt.sonarr.tv/ubuntu focal main" | sudo tee /etc/apt/sources.list.d/sonarr.list
          sudo apt update
          sudo apt install sonarr
          #install radarr
          sudo useradd radarr
          wget --content-disposition 'http://radarr.servarr.com/v1/update/master/updatefile?os=linux&runtime=netcore&arch=x64'
          tar -xvzf Radarr*.linux*.tar.gz
          sudo mv Radarr/ /opt
          sudo chown radarr:radarr /opt/Radarr 
          timeout 3m sudo /opt/Radarr/Radarr -nobrowser || ( [[ $? -eq 124 ]] && \echo "WARNING: Timeout reached for Jellyfin, but that's OK" )  & timeout 3m sudo npx localtunnel --port 8989 --subdomain radarr2 || ( [[ $? -eq 124 ]] && \echo "WARNING: Timeout reached for aria2, but that's OK" )
          cd ..
          mkdir data
          cd data
          mkdir Radarr
          mkdir Sonarr
          mkdir qbit
          sudo systemctl stop sonarr
          sudo cp -r /home/runner/.config/Radarr /home/runner/work/testcode/testcode/data/Radarr
          sudo cp -r /home/runner/.config/Sonarr /home/runner/work/testcode/testcode/data/Sonarr
          sudo git config --global user.name 'calvinjose789'
          sudo git config --global user.email 'calvinjose789@users.noreply.github.com'
          sudo git add .
          sudo git commit -am "Config File"
          sudo git push
          
