name: StartServer

on:
  schedule:
    - cron: 0 */6 * * *
  repository_dispatch:
  workflow_dispatch:

concurrency: 
  group: server
  cancel-in-progress: true

jobs:
  StartServer:
    runs-on: ubuntu-latest
    name: Server
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - name: Server Install
        run: |
          sudo apt-get install -y libmediainfo-dev
          wget https://mediaarea.net/repo/deb/repo-mediaarea_1.0-16_all.deb && dpkg -i repo-mediaarea_1.0-16_all.deb && apt-get update
          
          mkdir /home/runner/mount
          mkdir /home/runner/mounttwo
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone
          cat >  ~/.config/rclone/rclone.conf  << EOF
          ${{ secrets.RCLONE_CONFIG }}
          EOF
          sudo add-apt-repository -y ppa:qbittorrent-team/qbittorrent-stable
          sudo apt install qbittorrent-nox
          wget https://bin.equinox.io/c/VdrWdbjqyF/cloudflared-stable-linux-amd64.deb
          sudo dpkg -i cloudflared-stable-linux-amd64.deb
          sudo useradd radarr
          wget --content-disposition 'http://radarr.servarr.com/v1/update/master/updatefile?os=linux&runtime=netcore&arch=x64'
          tar -xzf Radarr*.linux*.tar.gz
          sudo mv Radarr/ /opt
          sudo chown radarr:radarr /opt/Radarr
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 2009837CBFFD68F45BC180471F4F90DE2A9B4BF8
          echo "deb https://apt.sonarr.tv/ubuntu focal main" | sudo tee /etc/apt/sources.list.d/sonarr.list
          sudo apt update
          sudo apt install sonarr
          sudo systemctl stop sonarr
          sudo chown sonarr:sonarr /var/lib/sonarr
          cd ~/
          mkdir .cloudflared
          cd .cloudflared
          cat << EOF >> cert.pem
          ${{ secrets.CF_CERT }}
          EOF
          cd ..
          sudo ln -s /usr/lib64/libmediainfo.so.17.10 /usr/lib64/libmediainfo.so.0
          sudo rclone mount drive:/ /home/runner/mount --allow-other --daemon --cache-db-purge --buffer-size 32M --use-mmap --dir-cache-time 4h --drive-chunk-size 16M --timeout 1h --vfs-cache-mode minimal --vfs-read-chunk-size 128M --vfs-read-chunk-size-limit 1G --fast-list
          sudo rclone mount requests:/ /home/runner/mounttwo --allow-other --daemon --cache-db-purge --buffer-size 32M --use-mmap --dir-cache-time 4h --drive-chunk-size 16M --timeout 1h --vfs-cache-mode minimal --vfs-read-chunk-size 128M --vfs-read-chunk-size-limit 1G --fast-list
          sleep 3s
          mono --debug /usr/lib/sonarr/bin/Sonarr.exe -nobrowser -data=/home/runner/mount/Config/Sonarr/ & /opt/Radarr/Radarr -nobrowser -data=/home/runner/mount/Config/Radarr/ & qbittorrent-nox --webui-port=7887 --profile=/home/runner/mount/Config/ &  cloudflared tunnel --url localhost:7887 --hostname ${{ secrets.QBIT_URL }} & cloudflared tunnel --url localhost:7878 --hostname ${{ secrets.RADARR_URL }} & cloudflared tunnel --url localhost:8989 --hostname ${{ secrets.SONARR_URL }}
