name: StartServer

on:
  repository_dispatch:
  workflow_dispatch:

concurrency: 
  group: server
  cancel-in-progress: true

jobs:
  StartServer:
    runs-on: ubuntu-latest
    name: Server
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - name: Server Install
        run: |
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone
          cat >  ~/.config/rclone/rclone.conf  << EOF
          ${{ secrets.RCLONE_CONFIG }}
          EOF
          sudo add-apt-repository -y ppa:qbittorrent-team/qbittorrent-stable
          sudo apt install qbittorrent-nox
          wget https://bin.equinox.io/c/VdrWdbjqyF/cloudflared-stable-linux-amd64.deb
          sudo dpkg -i cloudflared-stable-linux-amd64.deb
          sudo useradd radarr
          wget --content-disposition 'http://radarr.servarr.com/v1/update/master/updatefile?os=linux&runtime=netcore&arch=x64'
          tar -xzf Radarr*.linux*.tar.gz
          sudo mv Radarr/ /opt
          sudo chown radarr:radarr /opt/Radarr
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 2009837CBFFD68F45BC180471F4F90DE2A9B4BF8
          echo "deb https://apt.sonarr.tv/ubuntu focal main" | sudo tee /etc/apt/sources.list.d/sonarr.list
          sudo apt update
          sudo apt install sonarr
          sudo systemctl stop sonarr
          sudo chown sonarr:sonarr /opt/Sonarr
          mono --debug /usr/lib/sonarr/bin/Sonarr.exe -nobrowser -data=/var/lib/sonarr
