name: Swizz

on:
  repository_dispatch:
  workflow_dispatch:

concurrency: 
  group: Swizz
  cancel-in-progress: true

jobs:
  Swizz:
    runs-on: ubuntu-latest
    name: Swizz
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - name: Swizz
        run: |
           export TERMINFO=/usr/lib/terminfo
           wget git.io/swizzin
           sudo chmod +x swizzin
           sudo ./swizzin --unattended
